// <auto-generated />
namespace Softtek.Academy2018.ToDoListApp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class schema_changes_init_config : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(schema_changes_init_config));
        
        string IMigrationMetadata.Id
        {
            get { return "201802222146044_schema_changes_init_config"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
