// <auto-generated />
namespace ToDoListApp.MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitH : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitH));
        
        string IMigrationMetadata.Id
        {
            get { return "201803021918056_Init-H"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
